server:
  port: 8084

spring:
  application:
    name: prism-transcoder

  mongodb:
    uri: mongodb://localhost:27017/prism-transcoder-db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Custom Config
transcoder:
  ffmpeg-path: ffmpeg
  temp-dir: ${java.io.tmpdir}/prism-transcode
  hls:
    variants:
      - quality: 144p
        height: 144
        videoBitrate: 200k
        audioBitrate: 64k
        bandwidthKbps: 200
      - quality: 240p
        height: 240
        videoBitrate: 400k
        audioBitrate: 64k
        bandwidthKbps: 400
      - quality: 360p
        height: 360
        videoBitrate: 800k
        audioBitrate: 96k
        bandwidthKbps: 800
      - quality: 480p
        height: 480
        videoBitrate: 1400k
        audioBitrate: 128k
        bandwidthKbps: 1400
      - quality: 720p
        height: 720
        videoBitrate: 2800k
        audioBitrate: 128k
        bandwidthKbps: 2800
      - quality: 1080p
        height: 1080
        videoBitrate: 5000k
        audioBitrate: 192k
        bandwidthKbps: 5000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: prism-videos

logging:
  level:
    com.prism: DEBUG
