logging:
  level:
    com.prism: DEBUG
server:
  port: 8083 # Runs on port 8083

spring:
  codec:
    max-in-memory-size: 500MB # Only limits metadata/headers, not the file stream!
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: prism-videos
  region: us-east-1
  max-file-size: 5368709120 # 5GB
