logging:
  level:
    com.prism: DEBUG
server:
  port: 8084

spring:
  application:
    name: prism-transcoder
  mongodb:
    uri: ${MONGO_URI:mongodb://localhost:27017}/prism-transcoder-db
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# Custom Config
transcoder:
  ffmpeg-path: ffmpeg
  temp-dir: ${java.io.tmpdir}/prism-transcode
  hls:
    variants:
      - quality: 144p
        height: 144
        videoBitrate: 200k
        audioBitrate: 128k
        bandwidthKbps: 200
      - quality: 240p
        height: 240
        videoBitrate: 400k
        audioBitrate: 128k
        bandwidthKbps: 400
      - quality: 360p
        height: 360
        videoBitrate: 800k
        audioBitrate: 160k
        bandwidthKbps: 800
      - quality: 480p
        height: 480
        videoBitrate: 1400k
        audioBitrate: 192k
        bandwidthKbps: 1400
      - quality: 720p
        height: 720
        videoBitrate: 2800k
        audioBitrate: 256k
        bandwidthKbps: 2800
      - quality: 1080p
        height: 1080
        videoBitrate: 5000k
        audioBitrate: 320k
        bandwidthKbps: 5000

minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: prism-videos

management:
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}
