package com.prism.prism_auth.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.prism.prism_auth.model.enums.UserRole;
import com.prism.prism_auth.model.enums.UserStatus;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User entity representing a developer account in Prism.
 * 
 * Each user can create multiple Apps and manage API keys for those apps.
 * Users authenticate via email/password to the Dashboard.
 */
@Document(collection = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * MongoDB ObjectId (auto-generated by MongoDB)
     */
    @Id
    private String id;

    /**
     * Email - Primary identifier for login
     * UNIQUE index enforced at MongoDB level
     */
    @Indexed(unique = true)
    private String email;

    /**
     * Username - For display and optional alternative login
     * UNIQUE index enforced at MongoDB level
     */
    @Indexed(unique = true)
    private String username;

    /**
     * BCrypt hashed password (NEVER store plaintext)
     */
    private String passwordHash;

    /**
     * Profile information
     */
    private String firstName;
    private String lastName;

    /**
     * Account status - ACTIVE, SUSPENDED, DELETED, etc.
     */
    private UserStatus status;

    /**
     * User role - DEVELOPER or ADMIN
     * Determines permissions and access level
     */
    private List<UserRole> roles;

    /**
     * Email verification flag
     * User must verify email before they can create apps/keys
     */
    private Boolean emailVerified;
    private LocalDateTime emailVerifiedAt;

    /**
     * Security fields for brute force protection
     */
    private Integer failedLoginAttempts; // Track failed attempts
    private LocalDateTime lockedUntil; // Account locked until this timestamp

    /**
     * Login tracking
     */
    private LocalDateTime lastLoginAt;

    @Builder.Default
    private boolean accountNonLocked = true; // False = account locked by admin
    @Builder.Default
    private boolean accountNonExpired = true; // False = account expired
    @Builder.Default
    private boolean credentialsNonExpired = true; // False = password expired
    @Builder.Default
    private boolean enabled = true; // False = account disabled

    // Expiry dates for account and credentials
    private LocalDate credentialsExpiryDate;
    private LocalDate accountExpiryDate;

    /**
     * Optional: MFA/2FA support
     */
    private Boolean mfaEnabled;
    private String mfaSecret; // TOTP secret (encrypted)

    /**
     * Audit fields - automatically managed
     */
    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;

    // constructor for signup
    public User(String email, String username, String passString){
        this.email = email;
        this.username = username;
        this.passwordHash = passString;
        this.status = UserStatus.ACTIVE;
    }
    /**
     * Soft delete - set when user deletes account
     * Rather than hard delete, we mark it as deleted
     */
    private LocalDateTime deletedAt;

    /**
     * Helper method to check if account is locked due to brute force
     */
    public boolean isAccountLocked() {
        return lockedUntil != null && LocalDateTime.now().isBefore(lockedUntil);
    }

    /**
     * Helper method to check if account is active and verified
     */
    public boolean isActiveAndVerified() {
        return status == UserStatus.ACTIVE &&
                emailVerified != null && emailVerified &&
                deletedAt == null;
    }

    /**
     * Helper method to check if account is soft deleted
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }
}
