spring:
  application:
    name: prism-discovery
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # don't wait when sync is empty